version: "3"
services:
  db:
    image: mysql:5.7
      volumes:
        - .:/zhong
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: changeme
        MYSQL_DATABASE: zhong

  app:
    build: .
    environment:
      MYSQL_PASSWORD: changeme
    ports:
      - '8080:8000'